### ISSUE TITLE
History service is not included

### ISSUE THREAD

**Issue by narusevic** [schardtbc/iexcloud_api_wrapper#1]
**Describe the bug**
History is not included as exported method.

**To Reproduce**
1. index.ts file
2. There is no `export * from "./Services/History.service";`

**Expected behavior**
To use exported history method

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.3
 - Package version: 1.1.1

**Additional context**
Also history.ts::43 there is no `$` before `{closeOnly}`

**Comment by schardtbc** [comment]
Fixed issues with History.service use of destructured parameters; added three test cases. More would be useful; added to the export list in index.ts
