### ISSUE TITLE
Eroror: connect ETIMEOUT 

### ISSUE THREAD

**Issue by jjreego** [schardtbc/iexcloud_api_wrapper#11]
I have been using the iexcloud_api_wrapper for about a week. Yesterday I started getting the error:

(node:12816) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 104.197.97.64:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
(node:12816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

I added a try catch and just caught the error. Not sure how to fix this.

The code works for about 10-50 calls before the error starts showing up.

**Comment by schardtbc** [comment]
You are running into a rate limit on calls to the api.

**Comment by schardtbc** [comment]
I use the bottleneck package to rate limit the api calls from my app if needed. IEX allows only 100 calls per second max which under some conditions can be exceeded.

**Comment by schardtbc** [comment]
I will write up a note with code showing how to rate limit api calls.

**Comment by jjreego** [comment]
I think that will help. But the iexcloud does run slow at times. Does the
quote request allow for multiple stocks to be requested in a single message?

**Comment by schardtbc** [comment]
close this out.
