### ISSUE TITLE
quote("WDC") is not working 

### ISSUE THREAD

**Issue by AlexRudenko50** [schardtbc/iexcloud_api_wrapper#13]
Hello. I am Alex Rudenko.
I am new in this package.
I am linking this package with my node.js project.
I've installed this package by typing  "npm install iexcloud_api_wrapper"
and created "configure.env" file and set the IEXCLOUD_PUBLIC_KEY, IEXCLOUD_SECRET_KEY values with mine.
  
IEXCLOUD_API_VERSION = "beta"
IEXCLOUD_PUBLIC_KEY = "pk_..."
IEXCLOUD_SECRET_KEY = "sk_..."

I've added "configure.env" into .gitignore file
and then I have wrote following sample code to app.js file

const  iex = require( 'iexcloud_api_wrapper' )
const quote = async (sym) => {
  const quoteData = await iex.quote(sym);
  // do something with returned quote data
  console.log(quoteData)
};
quote("WDC");

when I execute this code, I've got following error.
(node:17280) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Request failed with status code 404
(node:17280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I'd like to know the reason.
Is there any issue in setting env file?
Looking forward to your reply
Best
Alex

**Comment by jjreego** [comment]
".env" worked for me. iexcloud.service.js was looking for a ".env" file.  The error message indicates that the symbol was not found. Try stepping through the JS code to pinpoint the error.

**Comment by schardtbc** [comment]
yes the environment file name is just simply .env
this seems to be standard in node projects

Let me know if you have further issues.

**Comment by jjreego** [comment]
Windows Notepad appended a "hidden"  .txt extension to my .env file
creating a ".env.txt" file.

Once I removed the ".txt" everything worked fine.

Thanks.

**Comment by AlexRudenko50** [comment]
Thanks for your reply.
I have solve the problem by your help.
But I encountered an other new issue during using your package.
for(let i in symbols)
{
let symbol = symbols[i].symbol;
quote(symbol);
}
I've added above code to get all info for my all symbols.
The length of symbols is 6700
it's working well for first 100~200 symbols.
but after that, it shows error like this
(node:22180) UnhandledPromiseRejectionWarning: Unhandled promise rejection
(rejection id: 11668): Error: socket hang up
it's getting more and more by time elapsed.
I would be thankful if you can let me know the reason.
Thanks
Best

**Comment by schardtbc** [comment]
the iex api is rate limited with a max of 100 requests per second. you would need to rate limit your calls to quote. I use the "bottleneck" package for this purpose.

As in the following code fragment

```
import { Connection, createConnection, EntityRepository } from "typeorm";

import {Company} from "../Entities/Company.entity"

import {loaderFactory} from "./Loader"

import { company } from "iexcloud_api_wrapper"

import Bottleneck from "bottleneck"

const makeLimiter = (mt: number, lmt: number=0) => {
    if (lmt === 0) {
      return new Bottleneck({
        maxConcurrent: 4,
        minTime: mt
    })
    } else {
      return new Bottleneck({
        maxConcurrent: 4,
        minTime: mt,
        reservoir: lmt, // initial value
        reservoirRefreshAmount: lmt,
        reservoirRefreshInterval: 24*60*60 * 1000, // mu
    })   
    }
  }
  
  const limiter = makeLimiter(20,0);

const companyService =  async (symbol: string): Promise<Company[]> =>{
    let result: Company[] = [];
    let tmp: any
    try {
    tmp = await limiter.schedule( () => company( symbol ))
    }
    catch( error ) {
        console.log(error.response.data);
        return result
    }
    // console.log(tmp)
    delete tmp.tags
    result = Array(Object.assign(new Company(),tmp));
    // console.log(result)
    return result
}

export const CompanyLoader = loaderFactory<Company>(companyService,Company)
```
