### ISSUE TITLE
Support chartIEXOnly for intraday endpoint

### ISSUE THREAD

**Issue by jjreego** [schardtbc/iexcloud_api_wrapper#14]
For the "intraday" endpoint how is chartIEXOnly specified?  (Limits the return of intraday prices to IEX only data.)  This is desired as chartIEXOnly data is free.

IEX Documentation:
chartIEXOnly | • Optional• boolean. Limits the return of intraday prices to IEX only data.

Current  iexcloud_api_wrapper implementation:

export declare const intraday: (symbol: string, chartLastN?: number, chartInterval?: number, changeFromClose?: boolean, chartReset?: boolean, chartSimplify?: boolean) => Promise<Intraday[]>;

**Comment by schardtbc** [comment]
iexcloud_api_wrapper/src/Services/IntradayIEXOnly.service.ts

defines  intradayIEXOnly()
