### ISSUE TITLE
Is there support for Recommendation-Trends?

### ISSUE THREAD

**Issue by jjreego** [schardtbc/iexcloud_api_wrapper#16]
Is there support for:

GET /stock/{symbol}/recommendation-trends

**Comment by schardtbc** [comment]
Note that this is a very expensive query, 1000 message counts per symbol. The data is updated very frequently 4 to 6 times per month for each symbol. I have it implemented in my rlang package iexcloudR.  Until IEX decreases message units per call and one is able to request new data only if updated after a target date then I do not know how to cost effectively utilize this data source. This is the reason it has not been a priority to implement. Given these facts, what are your thoughts. I have communicated my concerns to IEX.

**Comment by jjreego** [comment]
Like the news query, I only am most interested in fresh/current news and
recommendations.
So it would be nice to have to be able to only query for any new
recommendations every day.

Even better if there was a way to push new recommendations or new news. Old
information is much less valuable. You might only have seconds/milliseconds
to react to new news or recommendations.

The IEX system needs to be designed to get new market information out in
less than a second. Right now I poll everything about once a minute. It is
better than being blind.

I would rather pay more for fresh information then less for a lot of old
information.

**Comment by schardtbc** [comment]
IEX has no streaming endpoint for recommendations. New data arrives only 4 to 6 times per symbol per month on a random schedule. Even polling once per day would cost you 20000 messages/month per symbol. which for 100 symbols would be 2M messages/month. To catch a recommendation as close as possible to its release you would need to pole 4 times per day for 80000 messages per symbol.  Not viable in my estimation. $50/ month get you https://product.intrinio.com/pricing/zacks-analyst-ratings?show=true which seems more of what you are looking for.

**Comment by schardtbc** [comment]
I merged support for basic recommendation-trends, so you can experiment with the returned data.

**Comment by jjreego** [comment]
Thanks, I will start using the recommendation trends.  I have some
questions into Zacks on Intrino.

**Comment by schardtbc** [comment]
I have been exploring INTRINO, looks very good but somewhat expensive. They have a supported JavaScript wrapper , I have not tried it. Been writing my own R wrapper as that is much more useful for me personally. 

Bruce C. Schardt

On Jul 7, 2019, at 11:48 AM, jjreego <notifications@github.com> wrote:

Thanks, I will start using the recommendation trends. I have some
questions into Zacks on Intrino.
