### ISSUE TITLE
Company.service missing CEO

### ISSUE THREAD

**Issue by steven-mckeown-weareadaptive** [schardtbc/iexcloud_api_wrapper#3]
**Describe the bug**
CEO is missing from Company.service

**Expected behavior**
API docs include CEO in the payload
https://iexcloud.io/docs/api/#company

**Versions**
iexcloud_api_wrapper: 1.1.3

Edit:
KeyStats.service.d.ts is also missing the following:
ttmEPS
ttmDividendRate
dividendYield
nextDividendDate
exDividendDate
nextEarningsDate
peRatio
beta

**Comment by schardtbc** [comment]
Thanks for pointing out the issue. Now fixed.
