### ISSUE TITLE
OHLC.service.ts parses data incorrectly

### ISSUE THREAD

**Issue by steven-mckeown-weareadaptive** [schardtbc/iexcloud_api_wrapper#5]
**Describe the bug**
Set close twice wrongly, low is missing from payload, openTime and closeTime are wrong in OHLC.service.ts

is 
```
  result.close = data.close;
  result.openTime = data.openTime;
  result.closeTime = data.closeTime;
```

should be
```
  result.low = data.low;
  result.openTime = data.open.time;
  result.closeTime = data.close.time;
```

I tried to make a branch and create a pull request, but I don't have permission.

**Comment by schardtbc** [comment]
Fixed. Added result.symbol as well
